---
kind: pipeline
name: release-test

platform:
  os: linux
  arch: amd64

steps:
- name: export-keys
  image: msfjarvis/drone-decrypt-files:latest
  settings:
    decrypt_key:
      from_secret: key
    file_to_path_mapping:
    - "ci/keystore.cipher:keystore.jks|ci/props.cipher:keystore.properties"
  when:
    branch:
      exclude:
      - l10n_master
    event:
      exclude:
      - pull_request

- name: build
  image: msfjarvis/docker-android-sdk:ubuntu-standalone
  commands:
  - ./gradlew assembleRelease
  when:
    branch:
    - master

- name: telegram-deploy
  image: msfjarvis/drone-telegram:latest
  settings:
    artifacts: "app/build/outputs/apk/release/app-release.apk:substweaks"
    bot_token:
      from_secret: bot_token
    channel_id: -1001114098324
    major_minor: ci
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

...
