kind: pipeline
name: debug-test

steps:
  - name: build
    image: msfjarvis/docker-android-sdk:latest
    commands:
      - ./gradlew assembleDebug
    when:
      branch:
        - master

  - name: telegram-deploy
    image: msfjarvis/drone-telegram:latest
    settings:
      channel_id: -1001114098324
      artifact_path: app/build/outputs/apk/debug/app-debug.apk
      major_minor: ci
      filename: substweaks
      skip_changelog: true
      bot_token:
        from_secret: bot_token
    when:
      event:
        exclude:
          - pull_request
      branch:
        - master
